elasticsearch:
  image: elasticsearch
  command: elasticsearch -Des.network.bind.host=0.0.0.0
  ports:
    - '9200:9200'
    - '9300:9300'
kibana:
  image: kibana
  ports:
    - '5601:5601'
  links:
    - elasticsearch:elasticsearch
fluentd:
  image: issei/fluent-es
  links:
    - elasticsearch:elasticsearch
  ports:
    - '24224:24224'
nginx1:
  image: issei/nginx-fluentd
  ports:
    - '8081:80'
  log_driver: 'fluentd'
  links:
    - fluentd:fluentd
  log_opt:
    fluentd-address: 127.0.0.1:24224
    fluentd-tag: nginx.{{.FullID}}
nginx2:
  image: issei/nginx-fluentd
  ports:
    - '8082:80'
  log_driver: 'fluentd'
  links:
    - fluentd:fluentd
  log_opt:
    fluentd-address: 127.0.0.1:24224
    fluentd-tag: nginx.{{.FullID}}
